### ISSUE TITLE
node-sass python dependency

### ISSUE THREAD

**Issue by ragarcia26** [LeftyBC/node-yarn#1]
Some yarn dependencies require python which is not included in the alpine image.

Issue described here: https://github.com/nodejs/docker-node/issues/384
and further here: https://github.com/nodejs/docker-node/issues/282

Build log for error in question: 
```
Running with gitlab-ci-multi-runner 1.11.0 (33af656)
  on Cloud Engineering & Automation Runner #8 (1dcf9649)
Using Docker executor with image leftybc/node-yarn:latest ...
Pulling docker image leftybc/node-yarn:latest ...
Running on runner-1dcf9649-project-1117-concurrent-0 via ip-10-28-135-20...
Cloning repository...
Cloning into '/builds/graystone/hivemind-web'...
Checking out 2088f834 as add-pages...
Skipping Git submodules setup
$ mkdir -p public
$ yarn --force
yarn install v0.21.3
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.0.17: The platform "linux" is incompatible with this module.
info "fsevents@1.0.17" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Rebuilding all packages...
error /builds/graystone/hivemind-web/node_modules/node-sass: Command failed.
Exit code: 1
Command: sh
Arguments: -c node scripts/build.js
Directory: /builds/graystone/hivemind-web/node_modules/node-sass
Output:
Binary found at /builds/graystone/hivemind-web/node_modules/node-sass/vendor/linux-x64-51/binding.node
Testing binary
Binary has a problem: Error: Error relocating /builds/graystone/hivemind-web/node_modules/node-sass/vendor/linux-x64-51/binding.node: __strtod_internal: symbol not found
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at module.exports (/builds/graystone/hivemind-web/node_modules/node-sass/lib/binding.js:19:10)
    at Object.<anonymous> (/builds/graystone/hivemind-web/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
Building the binary locally
Building: /usr/local/bin/node /builds/graystone/hivemind-web/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/builds/graystone/hivemind-web/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.1
gyp info using node@7.5.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/builds/graystone/hivemind-web/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/builds/graystone/hivemind-web/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/builds/graystone/hivemind-web/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /builds/graystone/hivemind-web/node_modules/which/which.js:89:16
gyp verb `which` failed     at /builds/graystone/hivemind-web/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /builds/graystone/hivemind-web/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:112:15)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/builds/graystone/hivemind-web/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/builds/graystone/hivemind-web/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/builds/graystone/hivemind-web/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /builds/graystone/hivemind-web/node_modules/which/which.js:89:16
gyp verb `which` failed     at /builds/graystone/hivemind-web/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /builds/graystone/hivemind-web/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:112:15) code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (/builds/graystone/hivemind-web/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/builds/graystone/hivemind-web/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/builds/graystone/hivemind-web/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /builds/graystone/hivemind-web/node_modules/which/which.js:89:16
gyp verb `which` failed     at /builds/graystone/hivemind-web/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /builds/graystone/hivemind-web/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:112:15)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (/builds/graystone/hivemind-web/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/builds/graystone/hivemind-web/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/builds/graystone/hivemind-web/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /builds/graystone/hivemind-web/node_modules/which/which.js:89:16
gyp verb `which` failed     at /builds/graystone/hivemind-web/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /builds/graystone/hivemind-web/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:112:15) code: 'ENOENT' }
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/builds/graystone/hivemind-web/node_modules/node-gyp/lib/configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/builds/graystone/hivemind-web/node_modules/node-gyp/lib/configure.js:397:16)
gyp ERR! stack     at F (/builds/graystone/hivemind-web/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/builds/graystone/hivemind-web/node_modules/which/which.js:80:29)
gyp ERR! stack     at /builds/graystone/hivemind-web/node_modules/which/which.js:89:16
gyp ERR! stack     at /builds/graystone/hivemind-web/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /builds/graystone/hivemind-web/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:112:15)
gyp ERR! System Linux 3.13.0-98-generic
gyp ERR! command "/usr/local/bin/node" "/builds/graystone/hivemind-web/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /builds/graystone/hivemind-web/node_modules/node-sass
gyp ERR! node -v v7.5.0
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok 
Build failed with error code: 1
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR: Job failed: exit code 1
```

**Comment by LeftyBC** [comment]
Just pushed a new dockerfile with that change, it's building now.
